### PR TITLE
chore(release): v0.5.1

### PR DESCRIPTION
**Pull request by ravenclaw900**

### CODE REVIEW

**Comment by MichaIng** [comment]
MOTD updated and published the following tweet: https://twitter.com/DietPi_/status/1492942019047608320

**Comment by Joulinar** [comment]
@StephanStS
Could you publish it on Facebook pls?

**Comment by StephanStS** [comment]
> @StephanStS Could you publish it on Facebook pls?

Done.

**Comment by ravenclaw900** [comment]
Should I request a CVE?

**Comment by MichaIng** [comment]
What would be the benefit, aside of that we get a CVE-* GitHub link?

**Comment by ravenclaw900** [comment]
None that I can think of, since it's not a library and there's not going to be much discussion of it outside of what's already been done.

**Comment by MichaIng** [comment]
I agree, should be sufficient to communicate with our channels, so we don't need to cause review efforts for GitHub 🙂.

**Pull request merged**
