### PR TITLE
chore(release): 0.6.1

### PR DESCRIPTION
**Pull request by ravenclaw900**

### CODE REVIEW

**Comment by ravenclaw900** [comment]
I'm planning to release tomorrow.

**Comment by Joulinar** [comment]
2 issues I have using latest nightly v0.6.0-159-g329c9b0

1. on Edge browser I need to enter my password twice on login page before I'm logged in.
2. on Firefox browser the page is not loading. It stuck on `Connecting to API...` within the main window.

Both test done on same system using standalone dashboard.

**Comment by ravenclaw900** [comment]
Do you see any errors in the browser console on either of them?

**Comment by Joulinar** [comment]
on FF I have the following error message. FF is is not able to connect.

```
GETws://192.168.0.20:5252/ws
[HTTP/1.1 400 Bad Request 4ms]

	
GET
	ws://192.168.0.20:5252/ws
Status
400
Bad Request
VersionHTTP/1.1
Übertragen84 B (0 B Größe)

Firefox kann keine Verbindung zu dem Server unter ws://192.168.0.20:5252/ws aufbauen. index.e202bea1.js:27:7267
error { target: WebSocket, isTrusted: true, srcElement: WebSocket, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, … }
index.e202bea1.js:27:6404
Disconnected true index.e202bea1.js:27:6430
GETws://192.168.0.20:5252/ws
[HTTP/1.1 400 Bad Request 19ms]
```

**Comment by Joulinar** [comment]
I'm not sure if I try to catch it right on Edge browser. I get following

```
Connected
main.js?attr=vmIN40gh1emDZjfH3vB30KofLkYcw8k7dJohl1QfC-CjSXj5oTuCiBQl2KVrAL8V:2625 Abrufen hat das Laden beendet: GET "https://api.github.com/repos/ravenclaw900/DietPi-Dashboard/releases/latest".
fetchCallImpl @ main.js?attr=vmIN40gh1emDZjfH3vB30KofLkYcw8k7dJohl1QfC-CjSXj5oTuCiBQl2KVrAL8V:2625
window.fetch @ main.js?attr=vmIN40gh1emDZjfH3vB30KofLkYcw8k7dJohl1QfC-CjSXj5oTuCiBQl2KVrAL8V:2627
D @ index.e202bea1.js:27
z @ index.e202bea1.js:27
main.js?attr=vmIN40gh1emDZjfH3vB30KofLkYcw8k7dJohl1QfC-CjSXj5oTuCiBQl2KVrAL8V:2625 Abrufen hat das Laden beendet: POST "http://192.168.0.20:5252/login/".
fetchCallImpl @ main.js?attr=vmIN40gh1emDZjfH3vB30KofLkYcw8k7dJohl1QfC-CjSXj5oTuCiBQl2KVrAL8V:2625
window.fetch @ main.js?attr=vmIN40gh1emDZjfH3vB30KofLkYcw8k7dJohl1QfC-CjSXj5oTuCiBQl2KVrAL8V:2627
x @ index.e202bea1.js:27
(anonym) @ index.e202bea1.js:1
index.e202bea1.js:27 Disconnected true
index.e202bea1.js:27 Connected
```

Not sure why, but it seems to `Disconnected` me after trying to login first time.

**Comment by ravenclaw900** [comment]
Firefox sent more data than expected in the `Connection` header (`Connection: keep-alive, Upgrade` instead of just `Connection: Upgrade`). Fixed with https://github.com/ravenclaw900/DietPi-Dashboard/commit/cfead38a1310087708923de8263fcf32d448b23a. The problem with Edge was actually shared across all browsers when trying to log in without a fingerprint cookie or a token. Fixed in https://github.com/ravenclaw900/DietPi-Dashboard/commit/9b613d5ea098252d0cf304433eeb546b6938c48f.

**Comment by Joulinar** [comment]
Perfect. I guess it will be part of upcoming nightly release?

**Comment by ravenclaw900** [comment]
Yes, it should already be there. I've pushed one more change that makes notifications more noticeable, and I'm good to merge now.

**Comment by Joulinar** [comment]
I have one more. Seems more graphic than functional.

If you have a vertical screen
image

and making it full screen
image

is creating a strange graph

**Comment by ravenclaw900** [comment]
Okay, that's fixed too, and the graph will also resize when the menu is shrunk or grown: https://github.com/ravenclaw900/DietPi-Dashboard/commit/9dc86ae6254008a705d7f5d9ac751bff129c58c4.

**Pull request merged**
