### PR TITLE
chore(CODE_OF_CONDUCT): add code of conduct

### PR DESCRIPTION
**Pull request by ravenclaw900**

### CODE REVIEW

**Comment by MichaIng** [comment]
I thought about the same for DietPi itself. The Contributor Covenant CoC was my favourite candidate as well. The only thing that made me hesitate is that there should be a plan for consequently enforcing a CoC, in case of violation, especially through moderators tasks in forum and GitHub: Moderators need to be aware of it and follow some consistency about when and how to issue warnings and in case bans. And since I'm not aware of major violations until today, I didn't see the need to deal with this topic so far 😉.

It would be nice to have some consistency with this among DietPi and related projects. Probably we can talk about it one of the next weekly meetings, check for ways about how to issue warnings and bans in forum and GitHub, how strict we want to be, e.g. also differentiating between a simple hint, linking the CoC with a "😉", and in which case to do a formal step.

However, these were my probably too complicated thoughts, aiming to have a plan about how to enforce a CoC before adding one. It can be also the other way round: having public standards in the first place, and thinking about enforcement when there is a real incidence.

**Comment by ravenclaw900** [comment]
Feel free to hold off merging this until the meeting, and please let me know what's decided.

**Comment by Joulinar** [comment]
If you like, feel free to join our meeting 😄

**Comment by MichaIng** [comment]
As always, you're invited to join, when day time fits for you. Also, the dashboard is your baby, so of course feel free to merge to define your preferred community standard. I'd use the same CoC for DietPi anyway, and we can join/follow adding it after we discussed the enforcement topic 🙂.

**Review by MichaIng — APPROVED** [review]

**Pull request merged**
