### PR TITLE
feat(backend): allow using environment variables to set settings

### PR DESCRIPTION
**Pull request by ravenclaw900**
Adds an actual configuration library, uses `serde` without `serde_json`, and uses `jsonwebtoken` instead of `biscuit`. Increases binary size quite a bit, so now optimizes some packages for size instead of speed.

### CODE REVIEW

**Comment by ravenclaw900** [comment]
That's odd, the size reported in the artifact download is about .5 MB off from the actual downloaded size of the binary.

**Comment by MichaIng** [comment]
Cleans up our code but adds significant dependency code. Do you think it's worth it? For config parsing, the benefit is obvious, but what is the benefit of using `jsonwebtoken` instead of `biscuit`?

**Comment by ravenclaw900** [comment]
`jsonwebtoken` is actually more lightweight, but it requires `serde` to use it. `biscuit` (actually a fork of `jsonwebtoken`) is larger, with more dependencies, but it doesn't need `serde`. Output of `cargo-bloat` before (note that this is compiled on my own machine, for `gnu` instead of `musl`):
```
 File  .text     Size Crate
 5.6%  16.6% 411.9KiB h2
 4.0%  11.7% 290.8KiB hyper
 2.9%   8.5% 211.4KiB core
 2.4%   7.2% 179.3KiB rustls
 2.3%   6.7% 166.1KiB ring
 2.1%   6.2% 153.4KiB dietpi_dashboard
 1.9%   5.7% 142.0KiB std
 1.4%   4.2% 105.3KiB tokio
 1.2%   3.4%  84.6KiB [Unknown]
 1.1%   3.3%  82.6KiB warp
 1.0%   2.8%  70.5KiB data_encoding
 0.8%   2.3%  56.8KiB http
 0.7%   2.0%  50.5KiB toml
 0.6%   1.9%  46.4KiB alloc
 0.6%   1.6%  41.0KiB addr2line
 0.5%   1.4%  34.4KiB psutil
 0.4%   1.2%  31.1KiB biscuit
 0.4%   1.2%  30.7KiB miniz_oxide
 0.3%   0.9%  21.8KiB rustc_demangle
 0.3%   0.8%  20.1KiB hashbrown
 3.1%   9.2% 228.8KiB And 51 more crates. Use -n N to show more.
33.9% 100.0%   2.4MiB .text section size, the file size is 7.2MiB
```
After (with size optimizations):
```
 File  .text     Size Crate
 5.4%  15.6% 368.9KiB h2
 4.2%  12.1% 286.6KiB hyper
 2.8%   8.1% 191.0KiB dietpi_dashboard
 2.7%   7.8% 184.4KiB core
 2.3%   6.6% 156.5KiB rustls
 1.8%   5.3% 124.3KiB ring
 1.7%   5.0% 117.8KiB std
 1.5%   4.4% 104.8KiB tokio
 1.3%   3.8%  89.8KiB warp
 1.2%   3.4%  80.6KiB alloc
 1.1%   3.2%  76.5KiB figment
 1.1%   3.2%  75.3KiB [Unknown]
 1.0%   3.0%  70.3KiB jsonwebtoken
 0.6%   1.9%  44.0KiB http
 0.6%   1.8%  42.3KiB toml
 0.6%   1.7%  41.0KiB addr2line
 0.5%   1.5%  34.4KiB psutil
 0.3%   0.9%  21.8KiB rustc_demangle
 0.3%   0.8%  18.4KiB serde_json
 0.3%   0.8%  18.3KiB miniz_oxide
 3.0%   8.5% 201.9KiB And 60 more crates. Use -n N to show more.
34.6% 100.0%   2.3MiB .text section size, the file size is 6.7MiB
```
> Do you think it's worth it?
Honestly, now that I've done it, I'm not completely sure. I'll see the size comparison if I can find another config library that doesn't require `serde` and use that with `biscuit`. However, I might keep those optimizations on, while still disabling them for specific higher-performance crates.

**Comment by MichaIng** [comment]
Ah, and since `figment` requires `serde` anyway, switching to `jsonwebtoken` makes it actually lighter. I understand.

> Honestly, now that I've done it, I'm not completely sure.

Well, I mean the size of the assets with size optimisations is lower than latest `main` assets. Not sure whether the performance decrease for turning on size optimisation is in any way noticeable. Always good to have a look at alternatives, but while I did no performance tests, IMO it is fine as it is, simplifying (our) code for both, config parsing and token validation.

**Comment by ravenclaw900** [comment]
Originally I was using the [`jwts`](https://crates.io/crates/jwts/0.2.4) library, which was very lightweight, however I'm now trying to use [officially endorsed ones](https://jwt.io/libraries?language=Rust). One consolation, at least, is that we're still below the original Go binary size, when compressed. (1.4 MB vs. 2.3)

Actually, the compressed size is a lot less than I thought it would be, still smaller than `0.4.1`.

**Pull request merged**
