### PR TITLE
feat(dashboard): add CPU temperature

### PR DESCRIPTION
**Pull request by ravenclaw900**

### CODE REVIEW

**Comment by ravenclaw900** [comment]
@MichaIng, 2 things I don't really like with the current implementation.
1. The graph always shows in Celsius. Do you think it's worth a config file setting to decide between Celsius and Fahrenheit? (or maybe a frontend setting)?
2. The graph color. I'm actually running out of colors for the graph, do you have any ideas?

**Comment by MichaIng** [comment]
Probably a config file setting for °C vs °F is best, since we don't expect multiple people accessing one dashboard instance (do we?), so no need to have it client dependant.

Not sure about the colours, I think there are tools to generate a set of colour codes based on amount which are max different from each other.

**Comment by ravenclaw900** [comment]
Hmm... After (partially) implementing it, I realize that it will need to send the Celsius temperature anyway, to use it for the message calculation. Really, to not repeat code, the only place it would actually be used is in the graph, so I think that a setting in the frontend actually makes more sense.

**Comment by ravenclaw900** [comment]
Actually, even better would probably be to send it as a global setting, so that it can't be changed on-the-fly and mess up the graph, and would still be client-independent.

**Comment by ravenclaw900** [comment]
@MichaIng, should work (with the setting) now, please review.

**Comment by MichaIng** [comment]
Works well. Few things I recognised while playing around with the graphs, but not directly related to this PR:
- The `%` scale is still shown even when CPU usage is hidden. Temperature and `MB` scales are hidden when all related graphs are, as expected.
- It will be a rare case, but probably the `%` scale could move to the left, when the `MB` scale is hidden?
- `MB` and `MiB` are used inconsistently on graph and stats. I'm personally fans of using `MiB`/`GiB`/multi-byte units, as `Mega`/`Giga` is, to be precise, incorrect (power of 1000 vs power of 1024): https://en.wikipedia.org/wiki/Byte#Multiple-byte_units
- Since the network values are usually very small, they are not visible (at x-axis) when disk or RAM graphs are shown. They are actually `MiB/s`, isn't it? Probably worth to give them an own scale? Related is that the `MB` scale is not adjusted to `KB`/`KiB`, so  when only the network graphs are shown, the whole y-axis often shows `0 MB` from bottom to top.
- To quicker see graph and related scale, probably it would help to colour temperature and `%` scales the same way the related graphs are? That silver for temperature is not so different from white, probably a fresh colour palette with a more pregnant colour, like red or orange for temperature, would help as well then 😉.

**Review by MichaIng — DISMISSED** [review]

**Comment by ravenclaw900** [comment]
- That seems to be because I locked it to 0% - 100%. Since the change does stop the scale from disappearing, I think that it might be better to revert it.
- That would require some sort of workaround, but it could be done.
- I use the binary units (`MiB`, `GiB`) for RAM and swap, which seems to be the common usage for it. Everything else, from what I've seen, is measured with `MB` and `GB`. E.g.:
```
dietpi@rpi4:~ $ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        30G  4.4G   24G  16% /
/dev/mmcblk0p1  127M   34M   93M  27% /boot
(snip)
```
- I chose the MB scale because it was the most in the 'middle' of the other values (`KB` for network, `GB` for disk, `MiB` for RAM and swap). I think that having 2 scales with different information units might be slightly confusing, as it might look like it's sending `200GB` instead of `200KB` of data. Then again, network is its own thing, as it's per second instead of a constant measure. Adjusting the scale would also require a workaround of some sort, to detect when everything using the `MB` scale is off, and then flip the `CPU` scale.
- You mean something like this? I could add that, it works well.
Screen Shot 2022-05-30 at 11 09 09
I chose the silver color to be more neutral, so it wouldn't be confused with any of the temperature colors. What I would really prefer is a way to have the color change based on the temperature value, to match the reading on the side, but that doesn't currently seem to be possible.

**Comment by MichaIng** [comment]
> I've seen, is measured with `MB` and `GB`. E.g.:

Many scripts use the units inconsistently, either MB or just M while showing MiB. `df` indeed shows true power's of 1000 🤔. I like "MiB" since it is only unmistakable way to show the most commonly used power's of 1024 for any sizes in computer world.

> having 2 scales with different information units might be slightly confusing

Indeed, at least it would need to be made more distinguishable by using colours. In theory the units could be adjusted depending on highest value, so that having only network graphs selected, e.g. KiB/KB is used and hence network activity better visible.

But yeah, it's nothing urgent IMO, just something to keep in mind when having time and touching those graphs code anyway.

**Pull request merged**
